### ISSUE TITLE
Port from GObject to GLib

### ISSUE THREAD

**Issue by pro-panda** [sugarlabs/irc-activity#12]
Reference: https://github.com/orgs/sugarlabs/projects/5

**Comment by chimosky** [comment]
@pro-panda please close this as it has been fixed.

**Comment by quozl** [comment]
https://github.com/sugarlabs/irc-activity/commit/353a87b6efc2ee0c3ab9ca2264c71d271f55749e

A neglected fixes tag .. again.

A fixes tag is the word "Fixes" followed by the URL of the issue, and can be in any of;
- a commit message,
- a pull request initial comment,
- a pull request review or test comment,
- a pull request squash and merge commit message.
