### ISSUE TITLE
Port to Python 3.

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/irc-activity#14]

**Comment by quozl** [comment]
Note the unconventional use of `sys.path`.  This could hinder porting.  Reverse engineer the changes to `sys.path` and debug them.  You will see `sys.path` used in several files.  You should suspect them all.

**Comment by srevinsaju** [comment]
#16

**Comment by quozl** [comment]
An alternative to porting to Python 3 is to package a web activity using the webchat.freenode.net web app.
